### ISSUE TITLE
Minor regression

### ISSUE THREAD

**Issue by mrpink76** [manusa/actions-publish-docker#12]
Thanks for an awesome action!

Just wanted to notify you that the behavior of the action has changed in the last two commits to master.

I have reverted my build to using an old commit for now so it's not an issue for me so feel free to close this issue as you see fit :)

Previously I was able to publish my docker image to a private repository using the following config:

```
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@master
      with:
        name: cloud.canister.io:5000/MYUSERNAME/griffel
        tag: 0.1.$BUILD_NUMBER
        registry: cloud.canister.io:5000
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
```

Now I get the following error when using the master branch of this action:

```
Run manusa/actions-publish-docker@master
/usr/bin/docker run --name c27d31d2726404f9ee434692118b40940f3b35_8e4d7b --label c27d31 --workdir /github/workspace --rm -e frontend-dir -e backend-dir -e BUILD_NUMBER -e INPUT_NAME -e INPUT_TAG -e INPUT_REGISTRY -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_TAG_SCRIPT -e INPUT_INCLUDE_PULL_REQUESTS -e INPUT_DOCKERFILE_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/griffel-aurelia/griffel-aurelia":"/github/workspace" c27d31:d2726404f9ee434692118b40940f3b35
Loading input variables
Tag name for image: 0.1.$BUILD_NUMBER
Image name: cloud.canister.io:5000/cloud.canister.io:5000/***/griffel:0.1.$BUILD_NUMBER
Building docker image: cloud.canister.io:5000/cloud.canister.io:5000/***/griffel:0.1.$BUILD_NUMBER at path .
invalid argument "cloud.canister.io:5000/cloud.canister.io:5000/***/griffel:0.1.33" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
{ Error: Command failed: docker build -t cloud.canister.io:5000/cloud.canister.io:5000/***/griffel:0.1.$BUILD_NUMBER .
invalid argument "cloud.canister.io:5000/cloud.canister.io:5000/***/griffel:0.1.33" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
```

**Comment by manusa** [comment]
Hi @mrpink76 
I think your previous build worked because you configured around a "bug". 

Could you try to change your configuration to:
```
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@master
      with:
        name: MYUSERNAME/griffel
        tag: 0.1.$BUILD_NUMBER
        registry: cloud.canister.io:5000
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD
```
